# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/user/Documents/Code/PathOfExile/tradecompanion/views/tradewidget.ui',
# licensing of '/home/user/Documents/Code/PathOfExile/tradecompanion/views/tradewidget.ui' applies.
#
# Created: Mon Jul  1 18:01:12 2019
#      by: pyside2-uic  running on PySide2 5.12.4
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_TradeWidget(object):
    def setupUi(self, TradeWidget):
        TradeWidget.setObjectName("TradeWidget")
        TradeWidget.resize(464, 200)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TradeWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(TradeWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.buyer = QtWidgets.QLabel(TradeWidget)
        self.buyer.setObjectName("buyer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buyer)
        self.label_2 = QtWidgets.QLabel(TradeWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.item = QtWidgets.QLabel(TradeWidget)
        self.item.setObjectName("item")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.item)
        self.label_3 = QtWidgets.QLabel(TradeWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.price = QtWidgets.QLabel(TradeWidget)
        self.price.setObjectName("price")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_4 = QtWidgets.QLabel(TradeWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.stash = QtWidgets.QLabel(TradeWidget)
        self.stash.setObjectName("stash")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stash)
        self.label_5 = QtWidgets.QLabel(TradeWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.other = QtWidgets.QLabel(TradeWidget)
        self.other.setObjectName("other")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.other)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.time = QtWidgets.QLabel(TradeWidget)
        self.time.setObjectName("time")
        self.verticalLayout.addWidget(self.time)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.copy = QtWidgets.QPushButton(TradeWidget)
        self.copy.setObjectName("copy")
        self.horizontalLayout.addWidget(self.copy)
        self.whisper = QtWidgets.QPushButton(TradeWidget)
        self.whisper.setObjectName("whisper")
        self.horizontalLayout.addWidget(self.whisper)
        self.invite = QtWidgets.QPushButton(TradeWidget)
        self.invite.setObjectName("invite")
        self.horizontalLayout.addWidget(self.invite)
        self.trade = QtWidgets.QPushButton(TradeWidget)
        self.trade.setObjectName("trade")
        self.horizontalLayout.addWidget(self.trade)
        self.kick = QtWidgets.QPushButton(TradeWidget)
        self.kick.setObjectName("kick")
        self.horizontalLayout.addWidget(self.kick)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thanks = QtWidgets.QPushButton(TradeWidget)
        self.thanks.setObjectName("thanks")
        self.horizontalLayout_3.addWidget(self.thanks)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(TradeWidget)
        QtCore.QMetaObject.connectSlotsByName(TradeWidget)

    def retranslateUi(self, TradeWidget):
        TradeWidget.setWindowTitle(QtWidgets.QApplication.translate("TradeWidget", "Form", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("TradeWidget", "<b>Buyer</b>:", None, -1))
        self.buyer.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("TradeWidget", "<b>Item</b>:", None, -1))
        self.item.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("TradeWidget", "<b>Price</b>:", None, -1))
        self.price.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("TradeWidget", "<b>Stash</b>:", None, -1))
        self.stash.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("TradeWidget", "<b>Other</b>:", None, -1))
        self.other.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.time.setText(QtWidgets.QApplication.translate("TradeWidget", "TextLabel", None, -1))
        self.copy.setText(QtWidgets.QApplication.translate("TradeWidget", "Copy", None, -1))
        self.whisper.setText(QtWidgets.QApplication.translate("TradeWidget", "Whisper", None, -1))
        self.invite.setText(QtWidgets.QApplication.translate("TradeWidget", "Invite", None, -1))
        self.trade.setText(QtWidgets.QApplication.translate("TradeWidget", "Trade", None, -1))
        self.kick.setText(QtWidgets.QApplication.translate("TradeWidget", "Kick", None, -1))
        self.thanks.setText(QtWidgets.QApplication.translate("TradeWidget", "Thanks!", None, -1))

